# Based on: https://github.com/jdblischak/smk-simple-slurm
# Snakemake and Slurm Configuration File
# Update default values to match you local hardware
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem="{resources.mem_gb}G"
    --job-name=smk-{rule}-{wildcards}
    --time={resources.time}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --verbose
default-resources:
  - account=perrybe
  - partition=inv-iranui-fast,inv-iranui,inv-blade-g8-fast,inv-blade-g8,inv-bigmem-fast,inv-bigmem
  - qos=normal
  - time="02:00:00"
  - mem_gb=8
restart-times: 5
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 4
latency-wait: 600
jobs: 32
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: ilp
use-conda: True
use-singularity: True
reason: True
cluster-cancel: scancel
