# Pipeline Configuration File
###Global variables needed for analysis
BOWTIE_REFERENCE: "ref/IRBG74"
BOWTIE_ECOLIREF: "ref/ECOLI"
BOWTIE_PJG714REF: "ref/JG714"

# Tn5 Adapter Sequence to be trimmed from 5' Read End
IR_ELEMENT: "TATAAGAGACAG"
